/**
 * fetch-draws.js — EurekaLott
 * Tải Powerball draws từ Texas Lottery CSV
 * RAW ORDER — không sort
 * Output: draws-data.js (browser-compatible, không có module.exports)
 */

const https = require('https');
const fs    = require('fs');

function get(url) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (compatible; EurekaLott-Bot/1.0)',
        'Accept': 'text/csv,*/*',
      },
      timeout: 15000,
    }, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        return get(res.headers.location).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        return reject(new Error(`HTTP ${res.statusCode}`));
      }
      let body = '';
      res.on('data', chunk => body += chunk);
      res.on('end', () => resolve(body));
    });
    req.on('error', reject);
    req.on('timeout', () => { req.destroy(); reject(new Error('Timeout')); });
  });
}

(async () => {
  console.log('\n🎯 EurekaLott — Fetching Powerball draws (RAW ORDER)...\n');

  const url = 'https://www.texaslottery.com/export/sites/lottery/Games/Powerball/Winning_Numbers/powerball.csv';

  let body;
  try {
    body = await get(url);
    console.log(' [B] ✅ Texas Lottery CSV fetched');
  } catch (err) {
    console.error('❌ Failed to fetch Texas CSV:', err.message);
    process.exit(1);
  }

  /* Parse CSV
     Format: Powerball,month,day,year,n1,n2,n3,n4,n5,pb,multiplier */
  const draws = [];
  const lines = body.trim().split('\n');

  for (const line of lines) {
    const cols = line.trim().split(',').map(c => c.trim().replace(/"/g, ''));
    if (cols.length < 10 || cols[0] !== 'Powerball') continue;

    const month = cols[1].padStart(2, '0');
    const day   = cols[2].padStart(2, '0');
    const year  = cols[3];
    const date  = `${year}-${month}-${day}`;

    const w1 = parseInt(cols[4], 10);
    const w2 = parseInt(cols[5], 10);
    const w3 = parseInt(cols[6], 10);
    const w4 = parseInt(cols[7], 10);
    const w5 = parseInt(cols[8], 10);
    const pb = parseInt(cols[9], 10);

    if ([w1, w2, w3, w4, w5, pb].some(n => isNaN(n) || n < 1)) continue;

    draws.push({
      date,
      white: [w1, w2, w3, w4, w5],  // RAW ORDER — không sort
      powerball: pb,
    });
  }

  if (draws.length === 0) {
    console.error('❌ No draws parsed.');
    process.exit(1);
  }

  /* Sort by date ascending */
  draws.sort((a, b) => a.date.localeCompare(b.date));

  /* Write draws-data.js — browser compatible, NO module.exports */
  const json = JSON.stringify(draws, null, 2);

  fs.writeFileSync('draws-data.js',
`// draws-data.js — AUTO-GENERATED by fetch-draws.js
// Do not edit manually.
// Source: Texas Lottery CSV
// Last updated: ${new Date().toISOString()}
// ⚠️  white[] = RAW ORDER (thứ tự bóng rơi thực tế, KHÔNG sorted)

const draws = ${json};

// End of draws-data.js
`);

  console.log(`\n✅ draws-data.js written`);
  console.log(`   Total  : ${draws.length} draws`);
  console.log(`   Oldest : ${draws[0].date}`);
  console.log(`   Newest : ${draws[draws.length-1].date}`);
  console.log(`   Latest : white:[${draws[draws.length-1].white}] pb:${draws[draws.length-1].powerball}`);
  console.log('\n⚠️  No module.exports — browser compatible only\n');
})();
